title: WTF is Git?!
description: Git makes managing your projects and coursework much easier and is an essential skill in the software engineering industry. This repository lets you play with pushing and pulling to and from Git. Hosted by Sudo and Eng Soc
theme: jekyll-theme-minimal